### ISSUE TITLE
Triangle to voxel positions conversion

### ISSUE THREAD

**Issue by HybridDog** [appgurueu/voxelizer#1]
I have recently implemented the [vector.triangle function in vector_extras](https://github.com/HybridDog/vector_extras/blob/bc08421e209f57ef6369c14c7150ce0320b54b6e/init.lua#L1010). It converts a triangle defined by three (not necessarily integer) positions to a list of integer Minetest positions and returns the corresponding barycentric coordinates (they may be a bit inaccurate because the integer position is not (yet) projected back to the triangle plane).
As far as I can see, voxelizer uses [a different way to voxelize a triangle](https://github.com/appgurueu/voxelizer/blob/c8a7d0cd5940c8631a2582756b98a0b807b4d19e/main.lua#L129). I don't know which way works better; you can try vector.triangle if you want.

My implementation had the problem that holes appear between neighbouring triangles and I don't know if [I fixed it](https://github.com/HybridDog/vector_extras/commit/6f2bc919db534c1c0801af730a09900e8ef800ab) correctly.
Here's a [sphere approximated with triangles](https://gist.github.com/HybridDog/4fdf86760413e61ed17df36059c13ca0), where holes can be seen (happens when eps is 0):
![fot_2020-04-18-14:01:02_428284567](https://user-images.githubusercontent.com/3192173/79637168-4bc02480-817d-11ea-91cf-0126b8ca3e7c.jpg)
![fot_2020-04-18-14:00:53_950484330](https://user-images.githubusercontent.com/3192173/79637167-49f66100-817d-11ea-98e2-3b619135b84f.jpg)

**Comment by appgurueu** [comment]
My implementation uses simple vector math. A triangle can be seen as a 2d subspace of the vector space. We therefore have two basis vectors b1 and b2 (the sides of the triangle). Now we can iterate the subspace so that we get points on the triangle being x * b1 + y * b2 with x+y <= 1
