### ISSUE TITLE
Support for custom mesh files?

### ISSUE THREAD

**Issue by LucasSaragosa** [appgurueu/voxelizer#2]
This is not an error,
 I just want to know If it is possible to use your program on a custom mesh file. I have a custom mesh file, it only contains the vertex array data and the indices for the connecting faces in it. I want voxelise the mesh into minecraft PC in java. Could you tell me how I could do this?

**Comment by appgurueu** [comment]
> I have a custom mesh file, it only contains the vertex array data and the indices for the connecting faces in it.

Voxelizer currently only deals with Wavefront OBJ 3d models. You may like that Wavefront OBJ is pretty much what you describe: vertexes (`v <x> <y> <z>`) and faces. You will need texcoords (you could set them all to the same value, but you need some).

> I want voxelise the mesh into minecraft PC in java.

It is likely easily possible to port core algorithms to Java & MC, but this currently is for MT & uses Lua.

**Comment by LucasSaragosa** [comment]
Could you tell me the files which have the source code to voxelise the vertex arrays etc..?

**Comment by appgurueu** [comment]
> Could you tell me the files which have the source code to voxelise the vertex arrays etc..?

https://github.com/appgurueu/voxelizer/blob/master/main.lua

**Comment by appgurueu** [comment]
I only plan to support B3D and OBJ, the formats most frequently used in Minetest mods.
